import { GetSubscriptionApiResponseType } from '@/types';

export const SUBSCRIPTIONS_DUMMY_DATA: GetSubscriptionApiResponseType =
  {
    totalDocs: 3,
    results: 3,
    pages: 1,
    data: [
      {
        _id: 'subscription_id_1',
        user: {
          firstName: 'John',
          photo: '',
          email: 'john@example.com',
        },
        customer: 'customer_id_1',
        invoice: 'invoice_id_1',
        subscription: 'subscription_plan_1',
        interval: 'monthly',
        amount: 20,
        currency: 'USD',
        session: 'session_id_1',
        autoRenew: true,
        status: 'active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        __v: 0,
        endDate: '2024-12-31T23:59:59Z',
        startDate: '2024-01-01T00:00:00Z',
      },
      {
        _id: 'subscription_id_2',
        user: {
          firstName: 'Alice',
          photo: '',
          email: 'alice@example.com',
        },
        customer: 'customer_id_2',
        invoice: 'invoice_id_2',
        subscription: 'subscription_plan_2',
        interval: 'yearly',
        amount: 240,
        currency: 'USD',
        session: 'session_id_2',
        autoRenew: true,
        status: 'canceled',
        createdAt: '2024-02-01T00:00:00Z',
        updatedAt: '2024-02-01T00:00:00Z',
        __v: 0,
        endDate: '2025-01-31T23:59:59Z',
        startDate: '2024-02-01T00:00:00Z',
      },
      {
        _id: 'subscription_id_3',
        user: {
          firstName: 'Bob',
          photo: '',
          email: 'bob@example.com',
        },
        customer: 'customer_id_3',
        invoice: 'invoice_id_3',
        subscription: 'subscription_plan_3',
        interval: 'monthly',
        amount: 20,
        currency: 'USD',
        session: 'session_id_3',
        autoRenew: true,
        status: 'active',
        createdAt: '2024-03-01T00:00:00Z',
        updatedAt: '2024-03-01T00:00:00Z',
        __v: 0,
        endDate: '2024-12-31T23:59:59Z',
        startDate: '2024-03-01T00:00:00Z',
      },
      {
        _id: 'subscription_id_1',
        user: {
          firstName: 'John',
          photo: '',
          email: 'john@example.com',
        },
        customer: 'customer_id_1',
        invoice: 'invoice_id_1',
        subscription: 'subscription_plan_1',
        interval: 'monthly',
        amount: 20,
        currency: 'USD',
        session: 'session_id_1',
        autoRenew: true,
        status: 'active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        __v: 0,
        endDate: '2024-12-31T23:59:59Z',
        startDate: '2024-01-01T00:00:00Z',
      },
      {
        _id: 'subscription_id_1',
        user: {
          firstName: 'John',
          photo: '',
          email: 'john@example.com',
        },
        customer: 'customer_id_1',
        invoice: 'invoice_id_1',
        subscription: 'subscription_plan_1',
        interval: 'monthly',
        amount: 20,
        currency: 'USD',
        session: 'session_id_1',
        autoRenew: true,
        status: 'active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        __v: 0,
        endDate: '2024-12-31T23:59:59Z',
        startDate: '2024-01-01T00:00:00Z',
      },
      {
        _id: 'subscription_id_1',
        user: {
          firstName: 'John',
          photo: '',
          email: 'john@example.com',
        },
        customer: 'customer_id_1',
        invoice: 'invoice_id_1',
        subscription: 'subscription_plan_1',
        interval: 'monthly',
        amount: 20,
        currency: 'USD',
        session: 'session_id_1',
        autoRenew: true,
        status: 'active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        __v: 0,
        endDate: '2024-12-31T23:59:59Z',
        startDate: '2024-01-01T00:00:00Z',
      },
      {
        _id: 'subscription_id_1',
        user: {
          firstName: 'John',
          photo: '',
          email: 'john@example.com',
        },
        customer: 'customer_id_1',
        invoice: 'invoice_id_1',
        subscription: 'subscription_plan_1',
        interval: 'monthly',
        amount: 20,
        currency: 'USD',
        session: 'session_id_1',
        autoRenew: true,
        status: 'active',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
        __v: 0,
        endDate: '2024-12-31T23:59:59Z',
        startDate: '2024-01-01T00:00:00Z',
      },
    ],
  };
